# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cctok < Formula
  desc "CLI tool for tracking Claude Code & Codex token usage and costs"
  homepage "https://github.com/zK0G0w/cctok"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.4/cctok_darwin_amd64.tar.gz"
      sha256 "9aadb8cadad9b8038ab32756d21d9916f64a34711534b19d5325e4309be14a2a"

      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.4/cctok_darwin_arm64.tar.gz"
      sha256 "bad5530a9c57835e3613d3d28a5567371cf9873fa7e0423dd9a98e25769d0abb"

      define_method(:install) do
        bin.install "cctok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.4/cctok_linux_amd64.tar.gz"
      sha256 "90b505ec4ee8da5651ef427aa20837495ca7932aad8f2a83b9aca2fdd32e0736"
      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.4/cctok_linux_arm64.tar.gz"
      sha256 "ad891a48e707a57dfe1a311b49688f6acc288b2fcc045b1f947ec0d24c315cbe"
      define_method(:install) do
        bin.install "cctok"
      end
    end
  end
end
