# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cctok < Formula
  desc "CLI tool for tracking Claude Code & Codex token usage and costs"
  homepage "https://github.com/zK0G0w/cctok"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.1/cctok_darwin_amd64.tar.gz"
      sha256 "476242fbf15e05575af97cd49c628f9b74fcba42197f0658f746d8031a7e519b"

      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.1/cctok_darwin_arm64.tar.gz"
      sha256 "4d2b1fb9b1b237efd1a7516276d3a5abbb9a726ea7d325ac14a5701dee3a4c78"

      define_method(:install) do
        bin.install "cctok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.1/cctok_linux_amd64.tar.gz"
      sha256 "7012671054bfd689135cba620c0aa546bfb9528ad32b2dcb10711431c9334010"
      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.1/cctok_linux_arm64.tar.gz"
      sha256 "93c3091ec73ee9c7e05af316dc5f4678b90c0a0d498909654421b2ce5ffa962b"
      define_method(:install) do
        bin.install "cctok"
      end
    end
  end
end
