# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cctok < Formula
  desc "CLI tool for tracking Claude Code & Codex token usage and costs"
  homepage "https://github.com/zK0G0w/cctok"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.3/cctok_darwin_amd64.tar.gz"
      sha256 "155ec837802b6319dac7ddf54d84c23e9bc7fa7e9565dd9208e567c2a5966d27"

      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.3/cctok_darwin_arm64.tar.gz"
      sha256 "956fffebe3b0a10a89d44e82577c53ea7002f5a3bc4dfc43ed23b6413774e4b5"

      define_method(:install) do
        bin.install "cctok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.3/cctok_linux_amd64.tar.gz"
      sha256 "40049be1ee08446c9b44ebf74c41dc1ae0c80a18be81b1c2811c186af69eaec6"
      define_method(:install) do
        bin.install "cctok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zK0G0w/cctok/releases/download/v0.2.3/cctok_linux_arm64.tar.gz"
      sha256 "4e3c9d36435cf7dd78edc792944219b36a4382567d37fa6e8815c4c1bc6a96c6"
      define_method(:install) do
        bin.install "cctok"
      end
    end
  end
end
